# Generated by Django 4.2.3 on 2023-07-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_donation_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='donor_email',
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='donation',
            name='request',
            field=models.TextField(blank=True),
        ),
    ]
