# Generated by Django 4.2.3 on 2023-07-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0003_remove_donation_donor_email_donation_donor_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donor_address',
            field=models.CharField(max_length=255),
        ),
    ]
