# Generated by Django 4.2.3 on 2023-07-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0006_donations_delete_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='request',
            field=models.TextField(blank=True, null=True),
        ),
    ]
