# Generated by Django 4.2.3 on 2023-07-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0007_alter_donations_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='donor_mobile',
            field=models.CharField(max_length=20),
        ),
    ]
